### ISSUE TITLE
Is this a self-managed K8 cluster or can it leverage Amazon EKS?

### ISSUE THREAD

**Issue by eddiewang** [jwillker/production#2]
Hi John,

Just wanted to say thanks for making this an open source repo. I'm currently learning all the different fun parts of the self-managed cloud-stack (k8s, istio, terraform, etc.) and this is a really helpful resource.

I'm trying to better understand the core HA topology. From my understanding, this seems to be a self managed K8s, cluster - right? Or can this also use the Amazon EKS service?

The reason I am asking is because I currently use DigitalOcean K8s for prototyping, and GKE for production apps. Both have managed Kubernetes services, and I was wondering if there are any advantages in using their managed services rather than increasing the cognitive load needed for self-managing the cluster.

**Comment by jwillker** [comment]
Hi @eddiewang , I'm glad you liked the content.

For sure this is a self-managed K8s, but you cand adapt to use in any service like EKS, GKE, AKS, etc...

I'm thinking of writing for these use cases too, however currently in the short term, I would not have time to do this.

The HA topology is based in [HA with external etcd](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/ha-topology/#external-etcd-topology)
